version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "51223:25565"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.21"
      PLUGINS_FILE: "/extras/plugins.txt"
      # More aggressive settings for demo purposes
      MEMORY: "7G"
      JVM_OPTS: "-javaagent:/data/authlib-injector.jar=https://mcskin.com.cn/api/yggdrasil -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      ENFORCE_SECURE_PROFILE: "FALSE"
      REMOVE_OLD_MODS: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./plugins.txt:/extras/plugins.txt:ro
      - ./plugins:/plugins
      - ./authlib-injector-1.2.4.jar:/data/authlib-injector.jar:ro
      - ./config:/config
